services:

  service_1:
    image: service_1:latest
    container_name: service_1
    ports:
      - "5000:5000"
    environment:
      SERVICE_2: http://service_2:6000

    networks:
      - flask

  service_2:
    image: service_2:latest
    container_name: service_2
    ports:
      - "6000:6000"
    environment:
      SERVICE_1: http://service_1:5000
    networks:
      - flask


networks:
  flask:
    driver: bridge
